### ISSUE TITLE
Unable to find ligands in ligand expo db

### ISSUE THREAD

**Issue by kimeguida** [3D-e-Chem/kripo#2]
* Kripo version: 1.0.1
* Python version: 3.6.5
* Operating System: CentOS Linux 7 (Core)

### Description
I was trying to generate fingerprints for a set of PDB structures to later get pairwise similarities.
For some structures (e.g. 3N2V), Kripo could not find the ligand in the ligand-expo.db and could not generate their fingerprints.
The error message showed that the naming of the ligand was incomplete (residue number missing): "3n2v_JT5_1_A_".
I was expecting the ligand name to be "3n2v_JT5_1_A_0".

### What I Did

```
wget http://ligand-expo.rcsb.org/dictionaries/all-sdf.sdf.gz
kripo ligands import all-sdf.sdf.gz ligand-expo.db
wget https://files.rcsb.org/view/3N2V.pdb
wget https://files.rcsb.org/view/2RH1.pdb
ls 3N2V.pdb > pdb.list
ls 2RH1.pdb >> pdb.list
kripo generate --ligand-expo ligand-expo.db --no-fragmentation pdb.list frags.db phars.h5 fingerprints.db
```
I got the error:
```
Parsing 3N2V.pdb
Unable to find 3n2v_JT5_1_A_ in ligand expo db, skipping
No ligands found in 3N2V.pdb, skipping
```

**Comment by AJK-dev** [comment]
Thanks @kimeguida for reporting this.

This seems to be an issue due to the handling of residues with ID 0 by _atomium_. Although this was resolved in a newer version of _atomium_ ([0.11.1](https://atomium.samireland.com/changelog.html#release-0-11-1)), the newer versions of _atomium_ are unfortunately not fully backwards compatible and will break other parts of Kripo. I've created a small workaround that assumes that the residue ID is 0 when the residue ID is empty.
